version: 2

sources:
  - name: raw
    schema: raw
    database: analytics_dw
    tables:
      - name: customers
      - name: orders
      - name: payments

models:
  - name: stg_customers
    description: "Cleaned customers data from raw layer"
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

      - name: email
        tests:
          - not_null

  - name: stg_orders
    description: "Cleaned orders data from raw layer"
    columns:
      - name: order_id
        tests:
          - not_null
          - unique

      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id

  - name: stg_payments
    description: "Cleaned payments data from raw layer"
    columns:
      - name: payment_id
        tests:
          - not_null
          - unique

      - name: order_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id
